# Generated by Django 3.2.12 on 2022-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predmet',
            options={'verbose_name': 'Predmet', 'verbose_name_plural': 'Predmeti'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesori'},
        ),
        migrations.AlterModelOptions(
            name='ucenik',
            options={'verbose_name_plural': 'Ucenici'},
        ),
        migrations.AlterModelOptions(
            name='ucionica',
            options={'verbose_name_plural': 'Ucionice'},
        ),
        migrations.RenameField(
            model_name='ucionica',
            old_name='profesor_kvadratura',
            new_name='ucionica_kvadratura',
        ),
    ]
