# Generated by Django 3.2.12 on 2022-12-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet_naziv', models.CharField(max_length=100)),
                ('predmet_opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_ime', models.CharField(max_length=100)),
                ('profesor_prezime', models.CharField(max_length=100)),
                ('profesor_placa', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ucionica',
            fields=[
                ('predmet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.predmet')),
                ('ucionica_broj', models.PositiveIntegerField()),
                ('profesor_kvadratura', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucenik_ime', models.CharField(max_length=100)),
                ('ucenik_prezime', models.CharField(max_length=100)),
                ('ucenik_predmeti', models.ManyToManyField(to='main.Predmet')),
                ('ucenik_razrednik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='predmet',
            name='predmet_predavac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profesor'),
        ),
    ]
